# -*- coding: utf-8 -*-
"""EEG GUI final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0UJvlV-bQR4rjnSmJol-XKApENN13L8

# Psychiatric Disorder Classification based on EEG
## CIS189 Final Project

This notebook builds a gui that inputs a url with eeg data and outputs a dictionary that classifies the data into 1 of 7 psychiatric disorders, based on frequency band features, along with precision, recall and F1 metrics for each classification
"""

import pandas as pd
import numpy as np
import tkinter as tk
from tkinter import ttk
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import unittest

# CLASS 1: EEG Classifier

# Initializing the EEG Classifier class: Random Forest MVP
# Data is scaled to keep each diagnositic group balanced
# Data labels are then encoded 1 - 7

class EEG_classifier:
    def __init__(self):
        self.model = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        min_samples_leaf=5,
        class_weight='balanced',
        random_state=25
      )
        self.scaler = StandardScaler()
        self.le = LabelEncoder()
        self.data = None

    # Dataframe is loaded when user is prompted for url
    # Data is loaded, unnamed columns columns are dropped and education/IQ were filled
    # Exception is thrown if the url is faulty, or the shape of the data is incorrect

    def load_data(self, url):
        try:
            self.data = pd.read_excel(url)
            self.data = self.data.drop(columns=[col for col in self.data.columns if 'Unnamed' in col])
            self.data = self.data.drop(columns=['no.', 'eeg.date'], errors='ignore')
            self.data['education'] = self.data['education'].fillna(self.data['education'].median())
            self.data['IQ'] = self.data['IQ'].fillna(self.data['IQ'].median())
            return self.data

        except Exception as e:
            print(f"Error loading data: {e}")
            return None

    # data is validated by checking 3 things:
    # presence of main.disorder column
    # presence of at least one frequency band column
    # presence of missing data, which is appended to the empty list

    def validate_data(self, data):
        missing = []
        if 'main.disorder' not in data.columns:
            missing.append('main.disorder')

        for band in ['delta', 'theta', 'alpha', 'beta', 'gamma']:
            band_columns = [column for column in data.columns if band in column.lower()]
            if len(band_columns) == 0:
                missing.append(band)

        if len(missing) == 0:
            return True, None

        else:
            return False, f"Missing required data columns: {', '.join(missing)}"

    # Encodes labels, one-hot encodes sex
    # Splits then scales data, before returning 2 training and 2 test sets

    def preprocess_data(self, data):
        data = pd.get_dummies(data, columns=['sex'], drop_first=True).copy()
        data['disorder_label'] = self.le.fit_transform(data['main.disorder'])

        X = data.drop(columns=['main.disorder', 'disorder_label', 'specific.disorder'])
        y = data['disorder_label']

        X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=25, stratify=y)

        X_train_scaled = self.scaler.fit_transform(X_train)
        X_test_scaled = self.scaler.transform(X_test)

        return X_train_scaled, X_test_scaled, y_train, y_test

    # Train self.model using selected model
    # Generate predictions
    # Get classification_report as a dictionary
    # Filter disorder classes only, excluding accuracy, macro avg, etc

    def train_and_predict(self, X_train, X_test, y_train, y_test):
        self.model.fit(X_train, y_train)
        y_prediction = self.model.predict(X_test)
        report = classification_report(
        y_test, y_prediction, 
        labels=list(range(len(self.le.classes_))),
        target_names=list(self.le.classes_),
        output_dict=True)
        #class_names = list(self.le.classes_)
        results = {disorder: metrics 
        for disorder, metrics in report.items() 
        if disorder in self.le.classes_}
        #print("Results keys:", list(results.keys()))
        #print("Report keys:", list(report.keys()))
        #print("LE classes:", list(self.le.classes_))
        return results

    # Call load_data(url) —> if it returns None, return (False, error message)
    # Call validate_data(data) —> if valid is False, return (False, message)
    # Call preprocess_data(data) inside a try/except block
    # Call train_and_predict with the four arrays: X_train, y_train, X_test, y_test
    # Return classification report with specific metrics

    def run_classifier(self, url):
        data = self.load_data(url)
        if data is None:
            return False, "Could not load data from URL provided"

        valid, message = self.validate_data(data)
        if not valid:
            return False, message

        try:
            X_train, X_test, y_train, y_test = self.preprocess_data(data)
            results = self.train_and_predict(X_train, X_test, y_train, y_test)
        
        except Exception as e:
            return False, f"Processing error: {str(e)}"

        return True, results

# CLASS 3: Unit Tests for load_data and validate_data methods

# EEG_classifier unittests, running an example valid dataframe and an example invalid dataframe
# valid dataframe contains main.disorder column and at least one column of all 5 frequency bands
# invalid dataframe contains an invalid column name and incorrect values

class TestEEGClassifier(unittest.TestCase):
    def setUp(self):
      self.classifier = EEG_classifier()

    def test_load_data_valid(self):
      url = "https://raw.githubusercontent.com/bellajelly/EEG-Psychiatric-Disorder-Project/refs/heads/main/EEG.machinelearing_data_BRMH.xlsx"
      result = self.classifier.load_data(url)
      self.assertIsNotNone(result)

    def test_load_data_invalid(self):
      result = self.classifier.load_data('not_a_url')
      self.assertIsNone(result)

    def test_validate_data_valid(self):
      valid_data = pd.DataFrame({
    'main.disorder': ['Schizophrenia', 'Depression'],
    'delta.F3.F4': [0.5, 0.3],
    'theta.F3.F4': [0.4, 0.2],
    'alpha.F3.F4': [0.6, 0.1],
    'beta.F3.F4': [0.3, 0.5],
    'gamma.F3.F4': [0.2, 0.4]
})
      is_valid, message = self.classifier.validate_data(valid_data)
      self.assertTrue(is_valid)
      self.assertIsNone(message)

    def test_validate_data_invalid(self):
      invalid_data = pd.DataFrame({
    'incorrect_column': [1, 2, 3]
})
      is_valid, message = self.classifier.validate_data(invalid_data)
      self.assertFalse(is_valid)
      self.assertIsNotNone(message)

# CLASS 2: EEG Application GUI

# Tkinter GUI wraps EEG_classifier class
# Handles all user interaction, input validation display,
# and results rendering.

class EEGApp:
    def __init__(self, root):
        self.root = root
        self.root.title("EEG Psychiatric Disorder Classifier")
        self.root.configure(bg='#1a1a2e')
        self.root.minsize(800, 600)

        self.classifier = EEG_classifier()

        self._build_ui()

    def _build_ui(self):
        #Builds and lays out all tkinter widgets

        # ── Title ──────────────────────────────────────────
        title = tk.Label(
            self.root,
            text="EEG Psychiatric Disorder Classifier",
            font=('Courier', 16, 'bold'),
            bg='#1a1a2e', fg='#e0e0ff'
        )
        title.grid(row=0, column=0, columnspan=2, pady=(20, 10), padx=20)

        subtitle = tk.Label(
            self.root,
            text="Random Forest · 7-Class Classification",
            font=('Courier', 10),
            bg='#1a1a2e', fg='#7070aa'
        )
        subtitle.grid(row=1, column=0, columnspan=2, pady=(0, 20))

        # ── URL Entry ──────────────────────────────────────
        url_label = tk.Label(
            self.root,
            text="Dataset URL:",
            font=('Courier', 11),
            bg='#1a1a2e', fg='#e0e0ff'
        )
        url_label.grid(row=2, column=0, sticky='e', padx=(20, 8), pady=6)

        self.url_entry = tk.Entry(
            self.root,
            width=60,
            font=('Courier', 10),
            bg='#0f0f23', fg='#00ffcc',
            insertbackground='#00ffcc',
            relief='flat',
            bd=4
        )
        self.url_entry.grid(row=2, column=1, sticky='ew', padx=(0, 20), pady=6)

        # Pre-fill with default URL
        default_url = (
            "https://raw.githubusercontent.com/bellajelly/"
            "EEG-Psychiatric-Disorder-Project/refs/heads/main/"
            "EEG.machinelearing_data_BRMH.xlsx"
        )
        self.url_entry.insert(0, default_url)

        # ── Model Selector ─────────────────────────────────
        model_label = tk.Label(
            self.root,
            text="Model:",
            font=('Courier', 11),
            bg='#1a1a2e', fg='#e0e0ff'
        )
        model_label.grid(row=3, column=0, sticky='e', padx=(20, 8), pady=6)

        self.model_var = tk.StringVar(value="Random Forest")
        model_dropdown = ttk.Combobox(
            self.root,
            textvariable=self.model_var,
            values=["Random Forest"],
            state='readonly',
            font=('Courier', 10),
            width=30
        )
        model_dropdown.grid(row=3, column=1, sticky='w', padx=(0, 20), pady=6)

        # ── Run Button ─────────────────────────────────────
        self.run_button = tk.Button(
            self.root,
            text="▶  Run Classifier",
            font=('Courier', 12, 'bold'),
            bg='#00ffcc', fg='#1a1a2e',
            activebackground='#00ccaa',
            relief='flat',
            padx=20, pady=8,
            cursor='hand2',
            command=self._on_run
        )
        self.run_button.grid(row=4, column=0, columnspan=2, pady=16)

        # ── Error Label ────────────────────────────────────
        self.error_label = tk.Label(
            self.root,
            text="",
            font=('Courier', 10),
            bg='#1a1a2e', fg='#ff6b6b',
            wraplength=700
        )
        self.error_label.grid(row=5, column=0, columnspan=2, pady=(0, 8))

        # ── Status Label ───────────────────────────────────
        self.status_label = tk.Label(
            self.root,
            text="",
            font=('Courier', 10, 'italic'),
            bg='#1a1a2e', fg='#7070aa'
        )
        self.status_label.grid(row=6, column=0, columnspan=2, pady=(0, 8))

        # ── Results Treeview ───────────────────────────────
        tree_frame = tk.Frame(self.root, bg='#1a1a2e')
        tree_frame.grid(row=7, column=0, columnspan=2, sticky='nsew', padx=20, pady=(0, 20))

        columns = ('disorder', 'precision', 'recall', 'f1', 'support')
        self.tree = ttk.Treeview(
            tree_frame,
            columns=columns,
            show='headings',
            height=10
        )

        # Style the treeview
        style = ttk.Style()
        style.theme_use('clam')
        style.configure(
            'Treeview',
            background='#0f0f23',
            foreground='#e0e0ff',
            fieldbackground='#0f0f23',
            font=('Courier', 10),
            rowheight=28
        )
        style.configure(
            'Treeview.Heading',
            background='#2a2a4e',
            foreground='#00ffcc',
            font=('Courier', 10, 'bold')
        )
        style.map('Treeview', background=[('selected', '#2a2a6e')])

        # Column headings and widths
        self.tree.heading('disorder', text='Disorder')
        self.tree.heading('precision', text='Precision')
        self.tree.heading('recall', text='Recall')
        self.tree.heading('f1', text='F1 Score')
        self.tree.heading('support', text='Support')

        self.tree.column('disorder', width=250, anchor='w')
        self.tree.column('precision', width=100, anchor='center')
        self.tree.column('recall', width=100, anchor='center')
        self.tree.column('f1', width=100, anchor='center')
        self.tree.column('support', width=100, anchor='center')

        # Scrollbar
        scrollbar = ttk.Scrollbar(tree_frame, orient='vertical', command=self.tree.yview)
        self.tree.configure(yscrollcommand=scrollbar.set)

        self.tree.pack(side='left', fill='both', expand=True)
        scrollbar.pack(side='right', fill='y')

        # Make columns expandable
        self.root.columnconfigure(1, weight=1)
        self.root.rowconfigure(7, weight=1)

    def _on_run(self):
        # Called when run button is pressed
        # Clears previous state
        self._show_error("")
        self._clear_results()
        self._show_status("Running classifier... this may take a moment.")
        self.run_button.config(state='disabled')
        self.root.update()

        url = self.url_entry.get().strip()

        # Input validation
        if not url:
            self._show_error("Please enter a dataset URL.")
            self._show_status("")
            self.run_button.config(state='normal')
            return

        if not url.startswith('http'):
            self._show_error("URL must start with http:// or https://")
            self._show_status("")
            self.run_button.config(state='normal')
            return

        # Run the classifier
        success, payload = self.classifier.run_classifier(url)

        self.run_button.config(state='normal')

        if not success:
            self._show_error(payload)
            self._show_status("")
        else:
            self._show_status("Classification complete.")
            self._display_results(payload)

    def _display_results(self, results):
        # Displays metrics via treeview
        self._clear_results()

        for disorder, metrics in results.items():
            precision = f"{metrics['precision']:.3f}"
            recall = f"{metrics['recall']:.3f}"
            f1 = f"{metrics['f1-score']:.3f}"
            support = int(metrics['support'])
            self.tree.insert('', 'end', values=(disorder, precision, recall, f1, support))

    def _show_error(self, message):
        # Displays error message
        self.error_label.config(text=message)

    def _show_status(self, message):
        # Displays status message
        self.status_label.config(text=message)

    def _clear_results(self):
        # Clears all rows from treeview
        for row in self.tree.get_children():
            self.tree.delete(row)

if __name__ == "__main__":
    # Start the GUI application
    root = tk.Tk()
    app = EEGApp(root)
    root.mainloop()